---
- name: Scripts AFS
  when: use_afs
  block:
  - name: Disable garbage collection of PAGs
    copy:
      dest: /etc/sysctl.d/99-scripts-afs.conf
      content: |
        afs.GCPAGs = 0
    notify: apply sysctl
  - name: Configure NetRestrict
    template:
      dest: /usr/vice/etc/NetRestrict
      src: NetRestrict.j2
    notify: restart openafs-client
  - name: Configure better-mousetrapfs
    copy:
      dest: /etc/systemd/system/afs-000.mount
      content: |
        [Unit]
        Description=FUSE better mousetrap filesystem
        Requires=openafs-client.service
        Before=remote-fs.target
        After=openafs-client.service
        [Mount]
        What=/usr/sbin/better-mousetrapfs
        Where=/afs/000
        Type=fuse
        Options=defaults,nonempty,_netdev,nofail
        [Install]
        WantedBy=multi-user.target
    notify: restart better-mousetrapfs
    register: afs000_mount
  - name: Configure better-mousetrapfs mountpoint
    copy:
      dest: /usr/vice/etc/CellServDB.mousetrap
      content: |
        >000                    #better-mousetrapfs (see /usr/local/sbin/better-mousetrapfs)
    notify:
      - restart openafs-client
      - restart better-mousetrapfs
  - name: Start better-mousetrapfs
    systemd:
      daemon_reload: "{{ afs000_mount.changed }}"
      name: afs-000.mount
      enabled: yes
      state: started
    register: better_mousetrapfs_started
  - name: Enable afsagent
    systemd:
      name: "{{ item }}"
      enabled: yes
    loop:
      - scripts-afsagent.service
      - scripts-afsagent-startup.service
      - scripts-afsagent.timer
    when: has_daemon_keytab
  - name: Start afsagent
    systemd:
      name: "{{ item }}"
      state: started
    loop:
      - scripts-afsagent-startup.service
      - scripts-afsagent.timer
    when: has_daemon_keytab

# CellServDB maintains a mapping of cell names to IP addresses of servers
# serving them.

# Under normal operation, CellServDB.dist (which is distributed by the
# OpenAFS package) and CellServDB.local (which is normally empty, but can
# be used to add local AFS cells.)

# However, we patch OpenAFS's systemd unit file to instead concatenate
# CellServDB.local (which is Athena Ops provided database) and
# CellServDB.mousetrap (which is a bogus entry for better-mousetrapfs,
# which catches and kills 'find /afs').

# CellServDB.mousetrap must be concatenated at the end, as readdir on
# /afs returns cells in reverse order they are in CellServDB.
