---
- name: Scripts AFS
  when: use_afs
  block:
  - name: Install OpenAFS
    dnf:
      name:
        - fuse-better-mousetrapfs
        - scripts-kmod-openafs
        - scripts-openafs-client
        - scripts-openafs-authlibs
        - scripts-openafs-devel
        - scripts-openafs-krb5
        - tokensys
      state: present
  - name: Disable garbage collection of PAGs
    copy:
      dest: /etc/sysctl.d/99-scripts-afs.conf
      content: |
        afs.GCPAGs = 0
    notify: apply sysctl
  - name: Increase AFS performance
    ini_file:
      no_extra_spaces: yes
      path: /etc/sysconfig/openafs
      section: null
      option: AFSD_ARGS
      value: '"-afsdb -dynroot -fakestat -stat 25000 -daemons 100 -volumes 4000 -files 400000 -chunksize 19"'
    notify: restart openafs-client
  - name: Configure ThisCell
    copy:
      dest: /usr/vice/etc/ThisCell
      content: |
        athena.mit.edu
    notify: restart openafs-client
  - name: Configure CellAlias
    copy:
      dest: /usr/vice/etc/CellAlias
      content: |
        athena.mit.edu          athena
        csail.mit.edu           csail
        dev.mit.edu             dev
        lees.mit.edu            lees
        net.mit.edu             net
        ops.mit.edu             ops
        sipb.mit.edu            sipb
        andrew.cmu.edu          andrew
        acpub.duke.edu          acpub
    notify: restart openafs-client
  - name: Resize AFS cache
    copy:
      dest: /usr/vice/etc/cacheinfo
      content: |
        /afs:/usr/vice/cache:{{ afs_cache_size | default(10000000) }}
    notify: restart openafs-client
  - name: Configure SuidCells
    copy:
      dest: /usr/vice/etc/{{ item }}
      content: ""
    loop:
      - SuidCells
      - SuidCells.dist
      - SuidCells.local
    notify: restart openafs-client
  - name: Configure NetRestrict
    template:
      dest: /usr/vice/etc/NetRestrict
      src: NetRestrict.j2
    notify: restart openafs-client
  - name: Configure better-mousetrapfs
    copy:
      dest: /etc/systemd/system/afs-000.mount
      content: |
        [Unit]
        Description=FUSE better mousetrap filesystem
        After=openafs-client.service
        [Mount]
        What=/usr/sbin/better-mousetrapfs
        Where=/afs/000
        Type=fuse
        Options=defaults,nonempty
        [Install]
        WantedBy=multi-user.target
    notify: restart better-mousetrapfs
    register: afs000_mount
  - name: Configure better-mousetrapfs mountpoint
    copy:
      dest: /usr/vice/etc/CellServDB.mousetrap
      content: |
        >000                    #better-mousetrapfs (see /usr/local/sbin/better-mousetrapfs)
    notify:
      - restart openafs-client
      - restart better-mousetrapfs
  - name: Start openafs-client
    service:
      name: openafs-client
      enabled: yes
      state: started
    register: openafs_started
  - name: Start better-mousetrapfs
    systemd:
      daemon_reload: "{{ afs000_mount.changed }}"
      name: afs-000.mount
      enabled: yes
      state: started
    register: better_mousetrapfs_started
  - name: Start afsagent
    systemd:
      name: "{{ item }}"
      enabled: yes
      state: started
    loop:
      - scripts-afsagent.service
      - scripts-afsagent-startup.service
      - scripts-afsagent.timer

# CellServDB maintains a mapping of cell names to IP addresses of servers
# serving them.

# Under normal operation, CellServDB.dist (which is distributed by the
# OpenAFS package) and CellServDB.local (which is normally empty, but can
# be used to add local AFS cells.)

# However, we patch OpenAFS's systemd unit file to instead concatenate
# CellServDB.local (which is Athena Ops provided database) and
# CellServDB.mousetrap (which is a bogus entry for better-mousetrapfs,
# which catches and kills 'find /afs').

# CellServDB.mousetrap must be concatenated at the end, as readdir on
# /afs returns cells in reverse order they are in CellServDB.
