---
- name: restart better-mousetrapfs
  listen: restart openafs-client
  systemd:
    daemon_reload: yes
    name: afs-000.mount
    enabled: yes
    state: restarted
  when: not better_mousetrapfs_started.changed
