---
- name: Install dnf-automatic
  dnf:
    name: dnf-automatic
    state: present
- name: Configure dnf-automatic
  ini_file:
    path: /etc/dnf/automatic.conf
    section: "{{ item.section }}"
    option: "{{ item.option }}"
    value: "{{ item.value }}"
  loop:
    - section: commands
      option: download_updates
      value: "True"
    - section: commands
      option: apply_updates
      value: "False"
    - section: emitters
      option: emit_via
      value: stdio, command_email
    - section: command_email
      option: email_from
      value: root
    - section: command_email
      option: email_to
      value: root
- name: Enable dnf-automatic
  systemd:
    name: dnf-automatic.timer
    enabled: yes
    state: started
