---
- name: Run munin as non-root
  lineinfile:
    path: /etc/munin/munin-node.conf
    regexp: '^#?\s*{{ item.split()[0] }}\s'
    line: "{{ item }}"
  loop:
    - user munin
    - group munin
  notify: restart munin-node
- name: Configure sudoers
  copy:
    dest: /etc/sudoers.d/scripts-munin-node
    content: |
      Defaults:munin !syslog

      munin ALL=(root) SETENV: NOPASSWD: /etc/munin/plugins/postfix_mailqueue , /etc/munin/plugins/postfix_mailvolume , /etc/munin/plugins/sendmail* , /etc/munin/plugins/if_* , /etc/munin/plugins/if_err_eth2
- name: Run certain munin plugins as root
  copy:
    dest: /etc/munin/plugin-conf.d/zzz-scripts
    content: |
      [postfix*]
      user root
      env.logfile maillog
      env.logdir /var/log
      command sudo -E %c

      [sendmail]
      user root
      env.mspqueue /var/spool/clientmqueue
      command sudo -E %c
      
      [if_*]
      user root
      command sudo -E %c
      env.PATH /usr/kerberos/sbin:/usr/kerberos/bin:/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin:/root/bin
  notify: reconfigure munin-node
- name: Install scripts-munin-plugins
  dnf: name=scripts-munin-plugins state=present
  ignore_errors: yes
  notify: reconfigure munin-node
