---
- name: apply authselect
  command: /usr/bin/authselect apply-changes
- name: restart nslcd
  service: name=nslcd state=restarted
- name: restart nscd
  service: name=nscd state=restarted
  # Reloading nscd does not cause it to reread its configuration.
