---
- name: restart nrpe debian
  listen: restart nrpe
  service: name=nagios-nrpe-server state=restarted
  when: ansible_os_family == "Debian"
- name: restart nrpe redhat
  listen: restart nrpe
  service: name=nrpe state=restarted
  when: ansible_os_family == "RedHat"
  
