---
- name: Install post-transaction-actions plugin
  dnf: name=python3-dnf-plugin-post-transaction-actions
- name: Ensure /etc/dnf/plugins/post-transaction-actions.d exists
  file:
    path: /etc/dnf/plugins/post-transaction-actions.d/
    state: directory
- name: Configure dnf to drop unneeded executable permissions
  template:
    src: post-action.j2
    dest: /etc/dnf/plugins/post-transaction-actions.d/drop-permissions.action
- name: Ensure /etc/scripts exists
  file:
    path: /etc/scripts/
    state: directory
- name: Install allowed-setugid.list
  template:
    src: list.j2
    dest: /etc/scripts/allowed-setugid.list
  vars:
    items: "{{ allowed_setugid }}"
- name: Install allowed-filecaps.list
  template:
    src: list.j2
    dest: /etc/scripts/allowed-filecaps.list
  vars:
    items: "{{ allowed_filecaps }}"
- name: Install cron job
  copy:
    dest: /etc/cron.d/scripts-check-statoverride
    content: |
      MAILTO=scripts-root@mit.edu
      23 5 * * * root find / -xdev -not -perm -o=x -prune -o -type f -perm /ug=s -print | grep -Fxvf /etc/scripts/allowed-setugid.list | grep -ve ^/var/lib/mock/ | sed 's/^/Extra set[ug]id binary: /'
      27 5 * * * root find / -xdev -not -perm -o=x -prune -o -type f -print0 | xargs -0r /usr/sbin/getcap | cut -d' ' -f1 | grep -Fxvf /etc/scripts/allowed-filecaps.list | grep -ve ^/var/lib/mock/ | sed 's/^/Extra file_caps binary: /'
- name: Remove setugid on existing files
  file:
    path: "{{ item }}"
    mode: "ug-s"
  failed_when: False
  loop: "{{ drop_setugid }}"
- name: Remove file caps on existing files
  remove_filecaps:
    path: "{{ item }}"
  loop: "{{ drop_filecaps }}"
- name: Disable grub-boot-success
  systemd:
    name: grub-boot-success.timer
    masked: yes
    scope: global
