---
- name: Install iptables service
  dnf: name=iptables-services state=present
- name: Configure iptables modules
  copy:
    dest: /etc/modules-load.d/iptables.conf
    content: |
      nfnetlink
      nf_log_ipv4
      nf_log_ipv6
      xt_LOG
      xt_owner
      ipt_dscp
      ipt_MARK
      iptable_mangle
      iptable_filter
      ipt_REJECT
      ip6_tables
      ip6table_filter
      ip6t_REJECT
  notify: load modules
- name: Set socket fwmarks from packet marks
  copy:
    dest: /etc/sysctl.d/99-fwmark
    content: |
      net.ipv4.tcp_fwmark_accept = 1
  notify: apply sysctl
- name: Immediately load new modules
  meta: flush_handlers
- name: Configure iptables rules
  template:
    dest: /etc/sysconfig/iptables
    src: iptables.j2
  notify: reload iptables
- name: Configure ip6tables rules
  template:
    dest: /etc/sysconfig/ip6tables
    src: ip6tables.j2
  notify: reload ip6tables
- name: Start ip{,6}tables rules
  service:
    name: "{{ item }}"
    enabled: yes
    state: started
  loop:
    - iptables
    - ip6tables
