---
- name: Remove network-scripts
  dnf:
    name: network-scripts
    state: absent
- name: Remove NetworkManager
  dnf:
    name: NetworkManager
    state: absent
- name: lo
  block:
    - copy:
        dest: /etc/systemd/network/10-lo.network
        content: |
          [Match]
          Name=lo

          [Address]
          Address=127.0.0.1/8
          {% for vip in vips %}
          {% if vip.type is undefined or vip.type != 'director' %}
          [Address]
          Address={{vip.ip}}/32
          {% endif %}
          {% endfor %}
      notify: restart systemd-networkd
- name: vlan486
  block:
    - copy:
        when: vlan486_hwaddr is defined
        dest: /etc/systemd/network/10-vlan486.link
        content: |
          [Match]
          MACAddress={{vlan486_hwaddr}}

          [Link]
          Description=Public (VLAN 486)
          Name=vlan486
      notify: reboot
    - copy:
        dest: /etc/systemd/network/10-vlan486.network
        content: |
          [Match]
          MACAddress={{vlan486_hwaddr | default(ansible_default_ipv4.macaddress)}}

          [Network]
          {% for ip in mit_dns_servers %}
          DNS={{ip}}
          {% endfor %}
          {% if vlan486_address is defined %}
          Address={{vlan486_address}}/24
          {% else %}
          DHCP=ipv4
          {% endif %}

          [Route]
          Gateway=18.4.86.1
      notify: restart systemd-networkd
    - name: Remove network-scripts config file
      file:
        path: "{{item}}"
        state: absent
      loop:
        - /etc/sysconfig/network-scripts/ifcfg-{{ansible_default_ipv4.interface}}
        - /etc/sysconfig/network-scripts/ifcfg-eth0
        - /etc/sysconfig/network-scripts/ifcfg-vlan486
- name: vlan461
  when: vlan461_address is defined and vlan461_hwaddr is defined
  block:
    - copy:
        dest: /etc/systemd/network/10-vlan461.link
        content: |
          [Match]
          MACAddress={{vlan461_hwaddr}}

          [Link]
          Description=Backend (VLAN 461)
          Name=vlan461
      notify: reboot
    - copy:
        dest: /etc/systemd/network/10-vlan461.network
        content: |
          [Match]
          Name=vlan461

          [Address]
          Address={{vlan461_address}}/24

          {% for hostname in groups['sql'] + groups['scripts-real'] %}
          {% with info = hostvars[hostname] %}
          {% if info['vlan486_address'] | default(False) and info['vlan461_address'] | default(False) %}
          [Route]
          Destination={{ info['vlan486_address'] }}
          Gateway={{ info['vlan461_address'] }}
          {% endif %}
          {% endwith %}
          {% endfor %}
      notify: restart systemd-networkd
    - name: Remove network-scripts config file
      file:
        path: "{{item}}"
        state: absent
      loop:
        - /etc/sysconfig/network-scripts/ifcfg-eth1
        - /etc/sysconfig/network-scripts/ifcfg-vlan461
- name: Start systemd-networkd
  systemd:
    name: systemd-networkd
    state: started
    enabled: yes

