- name: Make Rawhide available
  dnf:
    name:
      - fedora-repos-rawhide
    state: present
  when: ansible_distribution_major_version|int <= 31
- name: "Install haproxy"
  dnf:
    name:
      - haproxy
    enablerepo: "{{ 'rawhide' if ansible_distribution_major_version|int <= 31 else '' }}"
    state: present
- name: "Install hatop"
  get_url:
    url: https://raw.githubusercontent.com/voretaq7/hatop/fa6ed17d763b6d02ee8d1eb61b40f15e6e8115ac/bin/hatop
    checksum: "sha256:93b539fc6be9f166b4b359f79ec1b08616b6d917dbef634ede2447e8fbda2333"
    dest: /usr/local/bin/hatop
    mode: '0755'
- name: "Install haproxyctl"
  pip:
    name: git+https://github.com/neurogeek/haproxyctl.git@8a10db76fdb7d6364a3ad99150c3ed37af439e71
