---
- include_tasks: 'install_{{ ansible_os_family }}.yml'
- name: Configure haproxy
  template:
    src: haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
  notify: reload haproxy
- file:
    path: /var/lib/haproxy/dev
    state: directory
- name: Configure haproxy logging
  copy:
    dest: /etc/rsyslog.d/haproxy.conf
    content: |
      # We have to load imuxsock here because this config is loaded
      # before the imuxsock module is loaded in rsyslog.conf;
      # this will cause a spurious warning about loading the module twice.
      module(load="imuxsock"
             SysSock.Use="off")
      input(type="imuxsock" Socket="/var/lib/haproxy/dev/log")

      local2.* /var/log/haproxy.log
  notify: restart rsyslog
- name: Configure logrotate to remove haproxy logs
  copy:
    dest: /etc/logrotate.d/haproxy
    content: |
      /var/log/haproxy.log {
          rotate 0
          daily
          missingok
          notifempty
          create 600 root root
          sharedscripts
          postrotate
              /usr/bin/systemctl kill -s HUP rsyslog.service >/dev/null 2>&1 || true
          endscript
      }
- name: Automatically restart haproxy on failure
  block:
    - file:
        path: /etc/systemd/system/haproxy.service.d
        state: directory
    - copy:
        dest: /etc/systemd/system/haproxy.service.d/10-scripts.conf
        content: |
          [Service]
          Restart=on-failure
      register: override
- name: Enable haproxy
  service:
    name: haproxy
    daemon_reload: "{{ override.changed }}"
    enabled: yes
    state: started
