---
- include_tasks: 'install_{{ ansible_os_family }}.yml'
- name: Configure haproxy
  template:
    src: haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
  notify: reload haproxy
- name: Enable haproxy
  service:
    name: haproxy
    enabled: yes
    state: started
# TODO: disable "client" when destination is off-subnet
# TODO: bind the vip addresses
# iptables -t mangle -A PREROUTING -p tcp -m socket -j MARK --set-xmark 1
# ip rule add fwmark 1 lookup 1
# ip route add local 0.0.0.0/0 dev lo table 1
# net.ipv4.conf.all.rp_filter = 0
# net.ipv4.conf.all.accept_local = 1
# net.ipv4.conf.all.log_martians = 1
