---
- name: Install mock and build dependencies
  dnf:
    name:
      - mock
      - redhat-lsb-core
      - rpmdevtools
      - cabal-install
      - rubygems
      - autoconf
    state: present
- name: Restrict mock to root
  block:
  - lineinfile:
      path: /etc/pam.d/mock
      insertafter: EOF
      line: "{{ item }}"
    loop:
      - "auth	required	pam_deny.so"
      - "account	required	pam_deny.so"
  - replace:
      path: /etc/pam.d/mock
      regexp: '^(auth|account)\s+.*\s+system-auth'
- name: Configure mock chroots
  vars:
    releasever: "{{ item[0] }}"
    arch: "{{ item[1] }}"
  template:
    src: chroot.cfg.j2
    dest: /etc/mock/scripts-fc{{ releasever }}-{{ arch }}.cfg
  loop:
    - ["30", "x86_64" ]
- name: Create local RPM repo
  file:
    path: /home/scripts-build/mock-local/
    owner: scripts-build
    state: directory
- stat:
    path: /home/scripts-build/mock-local/
  register: rpm_st
- stat:
    path: /home/scripts-build/mock-local/repodata/repomd.xml
  register: md_st
- name: Generate repo metadata
  command: /usr/bin/createrepo /home/scripts-build/mock-local/
  become: yes
  become_user: scripts-build
  when: (not md_st.stat.exists) or (rpm_st.stat.mtime > md_st.stat.mtime)
