---
- name: Install bind
  dnf:
    name:
      - bind
    state: present
- name: Configure named.mit.zones
  template:
    src: named.mit.zones.j2
    dest: /etc/named.mit.zones
  notify: reload named
- name: Configure named.conf
  blockinfile:
    path: /etc/named.conf
    block: |
      include "/etc/named.mit.zones";
  notify: reload named
- name: Configure named listen port
  vars:
    port: "{% if use_shackle %}54{% else %}53{% endif %}"
  lineinfile:
    path: /etc/named.conf
    insertafter: '^\s*options'
    regexp: '^\s*{{ item.split()[0] }}\s'
    line: "{{ item }}"
  notify: reload named
  loop:
    - "listen-on port {{ port }} { 127.0.0.1; };"
    - "listen-on-v6 port {{ port }} { ::1; };"
- name: Ensure named is listening on the correct port before continuing
  meta: flush_handlers
- name: Shackle
  when: use_shackle
  block:
  - name: Install shackle
    dnf: name=shackle state=present
  - name: Start shackle
    systemd:
      name: shackle.socket
      state: started
      enabled: yes
- name: Start named
  service:
    name: named
    state: started
    enabled: yes
- name: Configure DNS servers
  copy:
    dest: /etc/systemd/network/10-vlan486.network.d/dns.conf
    content: |
      [Network]
      DNS=127.0.0.1
      Domains=mit.edu
      [DHCPv4]
      UseDNS=false
  notify: restart systemd-networkd
- name: Remove temporary DNS servers
  file:
    path: /etc/systemd/network/10-vlan486.network.d/tempdns.conf
    state: absent
  notify: restart systemd-networkd
