---
- name: Install bind
  dnf:
    name:
      - bind
    state: present
- name: Configure named.mit.zones
  template:
    src: named.mit.zones.j2
    dest: /etc/named.mit.zones
  notify: reload named
- name: Configure named.conf
  blockinfile:
    path: /etc/named.conf
    block: |
      include "/etc/named.mit.zones";
  notify: reload named
- name: Start named
  service: name=named state=started
- name: Configure DNS servers
  ini_file:
    no_extra_spaces: yes
    path: /etc/sysconfig/network-scripts/ifcfg-{{ ansible_default_ipv4.interface }}
    section: null
    option: "{{ item.key }}"
    value: '"{{ item.value }}"'
  with_dict:
    DOMAIN: mit.edu
    DNS1: 127.0.0.1
