---
- name: Install scripts-httpd
  dnf:
    name:
      - scripts-httpd
      - scripts-mod_ssl
      - scripts-static-cat
      - mod_ldap
      - mod_fcgid
      - httpdmods
      - python3-ldap
      - python3-pyOpenSSL
      - logview
    state: present
- name: Configure httpd
  copy:
    dest: /etc/httpd/
    src: httpd/
    mode: preserve
  notify: reload httpd
- name: Configure mod_vhost_ldap
  template:
    dest: /etc/httpd/conf.d/vhost_ldap.conf
    src: vhost_ldap.conf.j2
  notify: reload httpd
- name: Configure vhost names
  template:
    dest: /etc/httpd/conf.d/scripts-vhost-names.conf
    src: scripts-vhost-names.conf.j2
  notify: reload httpd
- name: Install certificates
  copy:
    dest: /etc/pki/tls/certs/
    src: certs/
    mode: preserve
  notify: reload httpd
- name: Enable httpd
  service:
    name: httpd
    enabled: yes
    state: started
