---
- name: Install scripts-httpd
  dnf:
    name:
      - scripts-httpd
      - scripts-mod_ssl
      - mod_ldap
      - mod_fcgid
      - httpdmods
      - python3-ldap
      - python3-pyOpenSSL
    state: present
- name: Configure httpd
  copy:
    dest: /etc/httpd/
    src: httpd/
    mode: preserve
  notify: reload httpd
- name: Install certificates
  copy:
    dest: /etc/pki/tls/certs/
    src: certs/
    mode: preserve
  notify: reload httpd
- name: Enable httpd
  service:
    name: httpd
    enabled: yes
    state: started
