---
- name: Install scripts-httpd
  dnf:
    name:
      - scripts-httpd
      - scripts-mod_ssl
      - mod_ldap
      - mod_fcgid
      - httpdmods
      - python3-ldap
      - python3-pyOpenSSL
      - logview
    state: present
- name: Configure httpd
  copy:
    dest: /etc/httpd/
    src: httpd/
    mode: preserve
  notify: reload httpd
- name: Configure mod_vhost_ldap
  copy:
    dest: /etc/httpd/conf.d/vhost_ldap.conf
    content: |
      VhostLDAPEnabled on
      VhostLDAPUrl "{{ ldap_server }}ou=VirtualHosts,dc=scripts,dc=mit,dc=edu"
      VhostLDAPFallback notfound.example.com
- name: Install certificates
  copy:
    dest: /etc/pki/tls/certs/
    src: certs/
    mode: preserve
  notify: reload httpd
- name: Enable httpd
  service:
    name: httpd
    enabled: yes
    state: started
