---
- name: Install munin-node debian
  apt: name=munin-node state=present
  when: ansible_os_family == "Debian"
- name: Install munin-node redhat
  dnf: name=munin-node state=present
  when: ansible_os_family == "RedHat"
- name: Configure munin
  blockinfile:
    path: /etc/munin/munin-node.conf
    block: |
      allow ^127\.0\.0\.1$
      allow ^18\.4\.60\.65$
      allow ^18\.4\.60\.51$
  notify: restart munin-node
