---
- name: Install munin-node
  apt:
    name: munin-node
    state: present
- name: Configure munin
  blockinfile:
    path: /etc/munin/munin-node.conf
    block: |
      allow ^127\.0\.0\.1$
      allow ^18\.4\.60\.65$
      allow ^18\.4\.60\.51$
  notify: restart munin-node
