---
- name: Install MariaDB
  package:
    name:
      - mariadb-server
      - percona-toolkit
- name: Increase MariaDB open file limit
  block:
  - file:
      path: /etc/systemd/system/mariadb.service.d
      state: directory
  - copy:
      content: |
        [Service]
        LimitNOFILE=32768
        Environment="UMASK_DIR=0750" "UMASK=0640"
      dest: /etc/systemd/system/mariadb.service.d/99-scripts.conf
    register: override
    notify: restart mariadb
- name: Configure MariaDB
  template:
    dest: /etc/mysql/mariadb.conf.d/99-scripts-sql.cnf
    src: 99-scripts-sql.cnf.j2
  notify: restart mariadb
- name: Configure MariaDB clients
  template:
    dest: /etc/mysql/mariadb.conf.d/99-scripts-sql-clients.cnf
    src: 99-scripts-sql-clients.cnf.j2
