- name: Enable GSSAPIAuthentication
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '(?i)^#?\s*GSSAPIAuthentication\s'
    line: GSSAPIAuthentication yes
  notify: reload ssh
- name: Disable PasswordAuthentication
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '(?i)^#?\s*PasswordAuthentication\s'
    line: PasswordAuthentication no
  notify: reload ssh
- name: Update k5login
  copy:
    dest: /root/.k5login
    content: |
      {% for maintainer in maintainers %}
      {{ maintainer.username }}/root@ATHENA.MIT.EDU
      {% endfor %}
- name: Install Kerberos utilities
  block:
    - apt: name=krb5-user state=present
      when: ansible_os_family == "Debian"
    - dnf: name=krb5-workstation state=present
      when: ansible_os_family == "RedHat"
- name: Ensure krb5.conf.d exists
  file:
    path: /etc/krb5.conf.d
    state: directory
- name: Configure Kerberos
  copy:
    dest: /etc/krb5.conf
    src: krb5.conf
- name: Configure realm in debconf
  debconf: name=krb5-config question=krb5-config/default_realm vtype=string value=ATHENA.MIT.EDU
  when: ansible_os_family == "Debian"
