---
- name: Install nscd and nslcd
  dnf:
    name:
      - nscd
      - nss-pam-ldapd
    state: present
- name: Configure nscd for caching
  lineinfile:
    path: /etc/nscd.conf
    regexp: '(?i)^#?\s*{{ item.split()[0] }}\s+{{ (item.split()[1] in ("passwd group hosts services netgroup").split()) | ternary(item.split()[1] + "\s+", "") }}'
    line: "{{ item }}"
  loop:
    - threads 32
    - max-threads 128
    - negative-time-to-live passwd 5
    - negative-time-to-live group 5
    - suggested-size passwd 1999
    - persistent passwd no
    - suggested-size group 1999
    - persistent group no
    - suggested-size hosts 1999
  notify: restart nscd
- name: Enable nscd
  service:
    name: nscd
    enabled: yes
    state: started
- name: Configure nslcd
  copy:
    dest: /etc/nslcd.conf
    content: |
      uid nslcd
      gid ldap
      uri {{ ldap_server }}
      base dc=scripts,dc=mit,dc=edu
      base   group  ou=Groups,dc=scripts,dc=mit,dc=edu
      base   passwd ou=People,dc=scripts,dc=mit,dc=edu
      timelimit 120
      bind_timelimit 120
      idle_timelimit 3600
  notify: restart nslcd
- name: Enable nslcd
  service:
    name: nslcd
    enabled: yes
    state: started
- name: Install nss_nonlocal
  dnf:
    name: nss_nonlocal
    state: present
  when: use_nss_nonlocal
- name: Create authselect profile
  copy:
    dest: /etc/authselect/custom/scripts/
    src: authselect/
  notify: apply authselect
- name: Configure nsswitch
  template:
    dest: /etc/authselect/custom/scripts/nsswitch.conf
    src: nsswitch.conf.j2
  notify:
    - apply authselect
    - restart nscd
- name: Get current authselect profile
  command:
    /usr/bin/authselect current -r
  check_mode: no
  changed_when: False
  register: authselect_current
- name: Switch authselect profile
  command:
    /usr/bin/authselect select custom/scripts --force
  when: authselect_current.stdout != "custom/scripts"
