- name: Install rsyslog-relp debian
  apt: name=rsyslog-relp state=present
  when: ansible_os_family == "Debian"
- name: Install rsyslog-relp redhat
  dnf: name=rsyslog-relp state=present
  when: ansible_os_family == "RedHat"
- name: Increase max log length
  copy:
    dest: /etc/rsyslog.d/00-maxmessagesize.conf
    content: |
      $MaxMessageSize 64k
  notify: restart rsyslog
- name: Configure rsyslog
  copy:
    dest: /etc/rsyslog.d/scripts-syslog-client.conf
    content: |
      $ModLoad omrelp
      {% for rsyslog in rsyslogs %}
      {% if loop.first %}
      *.info :omrelp:{{ rsyslog }}:2514
      $ActionExecOnlyWhenPreviousIsSuspended on
      {% else %}
      & :omrelp:{{ rsyslog }}:2514
      {% endif %}
      {% endfor %}
      $ActionExecOnlyWhenPreviousIsSuspended off
  notify: restart rsyslog
