---
- name: Install logwatch
  dnf:
    name:
      - logwatch
    state: present
- name: Configure logwatch
  copy:
    dest: /etc/logwatch/
    src: logwatch/
    mode: preserve
# TODO: Enable logwatch.timer?
