all:
  vars:
    maintainers:
    - username: achernya
    - username: adehnert
      root_mail: adehnert-sipb@mit.edu
    - username: andersk
    - username: btidor
      root_mail: btidor-scripts@mit.edu
    - username: cela
    - username: cereslee
    - username: ezyang
    - username: geofft
      root_mail: null
    - username: glasgall
    - username: mitchb
    - username: tboning
    - username: quentin
    - username: vasilvv

    vips:
    - host: scripts-director.mit.edu
      ip: 18.4.86.132
      cidr_netmask: 24
      nic: vlan486
      type: director
    - host: scripts.mit.edu
      ip: 18.4.86.43
      cidr_netmask: 24
      nic: vlan486
      mail: True
    - host: scripts-cert.mit.edu
      ip: 18.4.86.50
      cidr_netmask: 24
      nic: vlan486
      type: cert
    - host: scripts-vhosts.mit.edu
      ip: 18.4.86.46
      cidr_netmask: 24
      nic: vlan486
      mail: True
    - host: scripts-test.mit.edu
      ip: 18.4.86.229
      cidr_netmask: 24
      nic: vlan486
    - host: sipb.mit.edu
      ip: 18.4.86.29
      cidr_netmask: 24
      nic: vlan486
      type: vhost

    rsyslogs:
    - 18.4.86.15  # log-flume
    - 18.4.86.16  # log-normal

    mit_dns_servers:
      - 18.0.70.160
      - 18.0.72.3
      - 18.0.71.151

    # Generated from http://kb.mit.edu/confluence/x/F4DCAg + whois, 2019-07-13
    mit_subnets:
      - 10/8
      - 18/11
      - 18.32/16
      - 18.33/16
      - 18.34/16
      - 18.38/16
      - 18.40/16
      - 18.42/16
      - 18.45/16
      - 18.47/16
      - 18.49/16
      - 18.50/16
      - 18.51/16
      - 18.53/16
      - 18.54/16
      - 18.55/16
      - 18.56/16
      - 18.58/16
      - 18.60/16
      - 18.61/16
      - 18.62/16
      - 18.63/16
      - 18.69/16
      - 18.70/16
      - 18.71/16
      - 18.72/16
      - 18.74/16
      - 18.75/16
      - 18.76/16
      - 18.77/16
      - 18.78/16
      - 18.79/16
      - 18.80/16
      - 18.81/16
      - 18.82/16
      - 18.83/16
      - 18.85/16
      - 18.87/16
      - 18.88/16
      - 18.89/16
      - 18.90/16
      - 18.93/16
      - 18.95/16
      - 18.100/16
      - 18.101/16
      - 18.102/16
      - 18.110/16
      - 18.113/16
      - 18.114/16
      - 18.115/16
      - 18.123/16
      - 18.124/16
      - 18.125/16
      - 18.127/16
      - 128.30/15
      - 128.52/16

  children:
    scripts-directors:
      hosts:
        george-lucas.mit.edu:
          vlan486_address: 18.4.86.220
          vlan486_hwaddr: 00:50:56:87:03:c5
        joss-whedon.mit.edu:
          vlan486_address: 18.4.86.226
          vlan486_hwaddr: 00:50:56:87:c2:23
        christopher-nolan.mit.edu:
          vlan486_address: 18.4.86.111
          vlan486_hwaddr: 00:50:56:87:d4:4e

    scripts-syslogs:
      hosts:
        log-flume.mit.edu: {}
        log-normal.mit.edu: {}

    scripts-ldap:
      hosts:
        doppelganger.mit.edu: {}
        alter-ego.mit.edu: {}
        body-double.mit.edu: {}

    scripts-real:
      children:
        scripts-real-test:
          vars:
            ansible_python_interpreter: /usr/bin/python3
            vips:
              - host: scripts-test.mit.edu
                ip: 18.4.86.229
                cidr_netmask: 24
            enable_testing_repo: yes
            # Don't Zephyr from dev servers
            syslog_client: no
            afs_cache_size: 500000
            use_local_ldap: no
            use_afs: yes
            use_scripts_openssh: yes
            use_nss_nonlocal: yes
            use_hesiod: yes
            use_scripts_localauth: yes
            use_accountadm: yes
            use_scripts_httpd: yes
            use_scripts_php: yes
            use_execsys: yes
            use_zephyr: yes
            use_autofs: yes
            use_moira: yes
            use_shackle: yes
            use_scripts_rubygems: yes
          hosts:
            quentin-scripts-f30.xvm.mit.edu:
              syslog_client: yes
            quentin-ansible-test.xvm.mit.edu:
              use_afs: yes
              use_scripts_openssh: yes
              use_nss_nonlocal: yes
              use_hesiod: yes
              use_scripts_localauth: yes
              use_accountadm: yes
              use_scripts_httpd: yes
              use_scripts_php: no
              use_execsys: yes
              use_zephyr: yes
              use_autofs: yes
              use_moira: yes
              use_shackle: yes
              use_scripts_rubygems: yes

            scripts-f30-test.xvm.mit.edu: {}

            jkoppel-scripts-test: {}
