all:
  vars:
    maintainers:
    - username: achernya
    - username: adehnert
      root_mail: adehnert-sipb@mit.edu
    - username: andersk
    - username: btidor
      root_mail: btidor-scripts@mit.edu
    - username: cela
    - username: cereslee
    - username: ezyang
    - username: geofft
      root_mail: null
    - username: glasgall
    - username: mitchb
    - username: tboning
    - username: quentin
    - username: vasilvv

    ip: "{{ lookup('dig', inventory_hostname) }}"

    vips:
    - host: scripts-director.mit.edu
      ip: 18.4.86.132
      cidr_netmask: 24
      nic: vlan486
      type: director
    - host: scripts.mit.edu
      ip: 18.4.86.43
      cidr_netmask: 24
      nic: vlan486
      mail: True
    - host: scripts-cert.mit.edu
      ip: 18.4.86.50
      cidr_netmask: 24
      nic: vlan486
      type: cert
    - host: scripts-vhosts.mit.edu
      ip: 18.4.86.46
      cidr_netmask: 24
      nic: vlan486
      mail: True
    - host: scripts-test.mit.edu
      ip: 18.4.86.229
      cidr_netmask: 24
      nic: vlan486
    - host: sipb.mit.edu
      ip: 18.4.86.29
      cidr_netmask: 24
      nic: vlan486
      type: vhost

    rsyslogs:
    - 18.4.86.15  # log-flume
    - 18.4.86.16  # log-normal

    mit_dns_servers:
      - 18.0.70.160
      - 18.0.72.3
      - 18.0.71.151

    # Generated from http://kb.mit.edu/confluence/x/F4DCAg + whois, 2019-11-18
    mit_subnets:
      - 10/8
      - 18/11
      - 128.30/15
      - 128.52/16

  children:
    scripts-directors:
      hosts:
        george-lucas.mit.edu:
          vlan486_address: 18.4.86.220
          vlan486_hwaddr: 00:50:56:87:03:c5
        joss-whedon.mit.edu:
          vlan486_address: 18.4.86.226
          vlan486_hwaddr: 00:50:56:87:c2:23
        christopher-nolan.mit.edu:
          vlan486_address: 18.4.86.111
          vlan486_hwaddr: 00:50:56:87:d4:4e

    scripts-syslogs:
      hosts:
        log-flume.mit.edu: {}
        log-normal.mit.edu: {}

    scripts-ldap:
      hosts:
        doppelganger.mit.edu: {}
        alter-ego.mit.edu: {}
        body-double.mit.edu: {}

    sql:
      vars:
        vlan461_address: "{{ ip | replace('18.4.86.', '172.21.0.') | replace('18.4.60.', '172.21.0.') }}"
      hosts:
        sql.mit.edu: {}
        primary-key.mit.edu: {}
        foreign-key.mit.edu: {}
        sliced-bread.mit.edu: {}

    scripts-real:
      children:
        scripts-real-prod:
          vars:
            vlan486_address: "{{ ip }}"
            vlan461_address: "{{ vlan486_address | replace('18.4.86.', '172.21.0.') }}"
          children:
            scripts-real-f30:
              vars:
                ansible_python_interpreter: /usr/bin/python3
              hosts:
                better-mousetrap.mit.edu:
                old-faithful.mit.edu:
                whole-enchilada.mit.edu:
                real-mccoy.mit.edu:
                golden-egg.mit.edu:
                #miracle-cure.mit.edu:
                #lucky-star.mit.edu:
            scripts-real-f20:
              hosts:
                bees-knees.mit.edu:
                cats-whiskers.mit.edu:
                pancake-bunny.mit.edu:
                busy-beaver.mit.edu:
                shining-armor.mit.edu:
        scripts-real-test:
          vars:
            ansible_python_interpreter: /usr/bin/python3
            vips:
              - host: scripts-test.mit.edu
                ip: 18.4.86.229
                cidr_netmask: 24
            enable_testing_repo: yes
            # Don't Zephyr from dev servers
            syslog_client: no
            afs_cache_size: 500000
            use_local_ldap: no
          hosts:
            quentin-scripts-f30.xvm.mit.edu:
              syslog_client: yes
            quentin-ansible-test.xvm.mit.edu: {}

            scripts-f30-test.xvm.mit.edu: {}

            jkoppel-scripts-test.xvm.mit.edu:
              maintainers:
                - username: jkoppel
            feral-purrbeast.xvm.mit.edu:
              maintainers:
                - username: cela
            poisonous-stamp.xvm.mit.edu:
              maintainers:
                - username: bpchen
            toasted-microwave.xvm.mit.edu:
              maintainers:
                - username: rihn
            miriamscripts.xvm.mit.edu:
              maintainers:
                - username: mrittenb
            anarchyscripts.xvm.mit.edu:
              maintainers:
                - username: jnoguera
