all:
  vars:
    maintainers:
    - username: achernya
    - username: adehnert
      root_mail: adehnert-sipb@mit.edu
    - username: andersk
    - username: btidor
      root_mail: btidor-scripts@mit.edu
    - username: cela
    - username: cereslee
    - username: ezyang
    - username: geofft
      root_mail: null
    - username: glasgall
    - username: mitchb
    - username: tboning
    - username: quentin
    - username: vasilvv

    vips:
    - host: scripts-director-new.mit.edu
      ip: 18.4.86.132
      cidr_netmask: 24
      nic: vlan486
    - host: scripts-new.mit.edu
      ip: 18.4.86.43
      cidr_netmask: 24
      nic: vlan486
      mail: True
    - host: scripts-cert-new.mit.edu
      ip: 18.4.86.50
      cidr_netmask: 24
      nic: vlan486
    - host: scripts-vhosts-new.mit.edu
      ip: 18.4.86.46
      cidr_netmask: 24
      nic: vlan486
      mail: True
    - host: scripts-test-new.mit.edu
      ip: 18.4.86.229
      cidr_netmask: 24
      nic: vlan486
    - host: sipb-new.mit.edu
      ip: 18.4.86.29
      cidr_netmask: 24
      nic: vlan486

    rsyslogs:
    - 18.4.86.15  # log-flume
    - 18.4.86.16  # log-normal

  children:
    scripts-directors:
      hosts:
        george-lucas.mit.edu:
          vlan486_address: 18.4.86.220
          vlan486_hwaddr: 00:50:56:87:03:c5
        joss-whedon.mit.edu:
          vlan486_address: 18.4.86.226
          vlan486_hwaddr: 00:50:56:87:c2:23
        christopher-nolan.mit.edu:
          vlan486_address: 18.4.86.111
          vlan486_hwaddr: 00:50:56:87:d4:4e

    scripts-syslogs:
      hosts:
        log-flume.mit.edu: {}
        log-normal.mit.edu: {}

    scripts-real:
      children:
        scripts-real-test:
          vars:
            ansible_python_interpreter: /usr/bin/python3
            vips:
              - host: scripts-test.mit.edu
                ip: 18.4.86.229
                cidr_netmask: 24
            # Don't Zephyr from dev servers
            syslog_client: no
            afs_cache_size: 500000
            run_local_ldap: no
            use_afs: yes
            use_scripts_openssh: yes
            use_nss_nonlocal: yes
            use_hesiod: yes
            use_scripts_localauth: yes
            use_accountadm: yes
            use_scripts_httpd: yes
            use_scripts_php: yes
            use_execsys: yes
            use_zephyr: yes
            use_autofs: yes
          hosts:
            quentin-scripts-f30.xvm.mit.edu:
              vars:
                syslog_client: yes
            quentin-ansible-test.xvm.mit.edu: {}
            scripts-f30-test.xvm.mit.edu: {}
