all:
  vars:
    k5login:
    - geofft/root@ATHENA.MIT.EDU
    - quentin/root@ATHENA.MIT.EDU
    - andersk/root@ATHENA.MIT.EDU
    - mitchb/root@ATHENA.MIT.EDU
    - ezyang/root@ATHENA.MIT.EDU
    - adehnert/root@ATHENA.MIT.EDU
    - achernya/root@ATHENA.MIT.EDU
    - glasgall/root@ATHENA.MIT.EDU
    - tboning/root@ATHENA.MIT.EDU
    - cereslee/root@ATHENA.MIT.EDU
    - btidor/root@ATHENA.MIT.EDU
    - vasilvv/root@ATHENA.MIT.EDU
    root_aliases:
    - andersk@mit.edu
    - quentin@mit.edu
    - mitchb@mit.edu
    - ezyang@mit.edu
    - xavid@mit.edu
    - adehnert-sipb@mit.edu
    - achernya@mit.edu
    - glasgall@mit.edu
    - tboning@mit.edu
    - cereslee@mit.edu
    - btidor-scripts@mit.edu
    - vasilvv@mit.edu

    vips:
    - host: scripts-director-new.mit.edu
      ip: 18.4.86.132
      cidr_netmask: 24
      nic: vlan486
    - host: scripts-new.mit.edu
      ip: 18.4.86.43
      cidr_netmask: 24
      nic: vlan486
    - host: scripts-cert-new.mit.edu
      ip: 18.4.86.50
      cidr_netmask: 24
      nic: vlan486
    - host: scripts-vhosts-new.mit.edu
      ip: 18.4.86.46
      cidr_netmask: 24
      nic: vlan486
    - host: scripts-test-new.mit.edu
      ip: 18.4.86.229
      cidr_netmask: 24
      nic: vlan486
    - host: sipb-new.mit.edu
      ip: 18.4.86.29
      cidr_netmask: 24
      nic: vlan486
    - host: webzephyr.mit.edu
      ip: 18.181.0.49
      cidr_netmask: 16
      nic: vlan181

  children:
    scripts-directors:
      hosts:
        george-lucas.mit.edu:
          vlan181_address: 18.181.0.220
          vlan181_hwaddr: 00:50:56:87:9b:7d
          vlan486_address: 18.4.86.220
          vlan486_hwaddr: 00:50:56:87:03:c5
        joss-whedon.mit.edu:
          vlan181_address: 18.181.0.226
          vlan181_hwaddr: 00:50:56:87:2c:8e
          vlan486_address: 18.4.86.226
          vlan486_hwaddr: 00:50:56:87:c2:23
        christopher-nolan.mit.edu:
          vlan181_address: 18.181.0.111
          vlan181_hwaddr: 00:50:56:87:07:a0
          vlan486_address: 18.4.86.111
          vlan486_hwaddr: 00:50:56:87:d4:4e
