- import_playbook: scripts-directors.yml

- import_playbook: scripts-directors-cib.yml

- import_playbook: scripts-proxy.yml

- import_playbook: scripts-syslog.yml

- import_playbook: scripts-real.yml

