- hosts: scripts-directors
  vars:
    network_allow_service_restart: false
    network_ether_interfaces:
    - device: vlan181
      hwaddr: "{{ vlan181_hwaddr }}"
      cidr: "{{ vlan181_address }}/16"
      gateway: 18.181.0.1
      dns_nameservers:
      - 18.70.0.160
      - 18.72.0.3
      - 18.71.0.151
      dns_search: mit.edu
      options:
      - metric 1
      - up ip route add 18.181.0.0/16 table 181 dev vlan181
      - up ip route add default table 181 via 18.181.0.1 dev vlan181
      - up ip rule add from 18.181.0.0/16 table 181
      - down ip rule del table 181
    - device: vlan486
      hwaddr: "{{ vlan486_hwaddr }}"
      cidr: "{{ vlan486_address }}/24"
      gateway: 18.4.86.1
      options:
      - metric 2
      - up ip route add 18.4.86.0/24 table 486 dev vlan486
      - up ip route add default table 486 via 18.4.86.1 dev vlan486
      - up ip rule add from 18.4.86.0/24 table 486
      - down ip rule del table 486
    pacemaker_corosync_ring_interface: vlan486
    pacemaker_corosync_group: scripts-directors
  pre_tasks:
  - name: Upgrade packages
    apt:
      upgrade: dist
  - name: Install packages
    apt:
      name: "{{ item }}"
      state: present
    with_items:
    - open-vm-tools
    - open-vm-tools-dkms
    - exim4-daemon-light
    - resolvconf
    - mlocate
    - lighttpd
    - lighttpd-mod-magnet
    - munin-node
    - pacemaker
    - pacemaker-cli-utils
    - crmsh
    - ldirectord
    - tcpdump
    - tshark
    - strace
  - systemd: name=ldirectord enabled=no
  - include_role: name=udev_rename_netiface
  - include_role: name=network_interface
  - when: udev_rename_netiface_config_changed or ether_result.changed
    command: "true"
    notify:
      - reboot
      - munin reconfigure
      - setup
  tasks:
  - include_role: name=ldirectord-status
  - include_role: name=lvs-iptables
  - name: Configure munin
    blockinfile:
      path: /etc/munin/munin-node.conf
      block: |
        allow ^127\.0\.0\.1$
        allow ^18\.187\.1\.128$
        allow ^18\.181\.0\.65$
        allow ^18\.181\.0\.51$
    notify: restart munin-node
  - name: Install munin cps plugin
    copy:
      dest: /etc/munin/plugins/cps_1_0
      src: files/cps_
      mode: 0755
    notify: restart munin-node
  - name: Create munin cps plugin links
    file:
      src: /etc/munin/plugins/cps_1_0
      dest: "/etc/munin/plugins/cps_{{ item }}_0"
      state: link
    with_items:
      - 2
      - 3
    notify: restart munin-node
  - name: Update /etc/aliases
    lineinfile:
      path: /etc/aliases
      regexp: '^root:'
      line: "root: {{ root_aliases|join(', ') }}"
    notify: newaliases
  - name: Install /etc/lighttpd/scripts-maint
    synchronize:
      dest: /etc/lighttpd/scripts-maint/
      src: files/scripts-maint/
      delete: yes
  - name: Install /etc/lighttpd/scripts-maint.lua
    copy:
      dest: /etc/lighttpd/scripts-maint.lua
      src: files/scripts-maint.lua
  - name: Configure lighttpd
    copy:
      dest: /etc/lighttpd/lighttpd.conf
      src: files/scripts-maint-lighttpd.conf
    notify: restart lighttpd
  - name: Load IPVS modules
    copy:
      dest: /etc/modules-load.d/lvs.conf
      content: |
        ip_vs_dh
        ip_vs_ftp
        ip_vs
        ip_vs_lblc
        ip_vs_lblcr
        ip_vs_lc
        ip_vs_nq
        ip_vs_rr
        ip_vs_sed
        ip_vs_sh
        ip_vs_wlc
        ip_vs_wrr
    notify:
      - load modules
      - reload sysctl
  - name: Configure sysctl
    copy:
      dest: /etc/sysctl.d/lvs.conf
      content: |
        net.ipv4.ip_forward=1
        net.ipv4.vs.expire_quiescent_template = 1
    notify: reload sysctl
  - include_role: name=pacemaker-corosync
    vars:
      haveged_enabled: false
      pacemaker_enable_nodelist: false
  - name: Configure ldirectord
    copy:
      dest: /etc/ha.d/ldirectord.cf
      src: files/ldirectord.cf
  handlers:
  - name: newaliases
    command: newaliases
  - name: restart lighttpd
    service: name=lighttpd state=restarted
  - name: load modules
    service: name=systemd-modules-load state=restarted
  - name: reload sysctl
    service: name=systemd-sysctl state=restarted
  - name: reboot
    include_tasks: reboot.yaml
  - name: munin reconfigure
    shell: munin-node-configure --suggest --shell --remove-also | sh
    notify: restart munin-node
  - name: restart munin-node
    service: name=munin-node state=restarted
  - name: setup
    setup:
