- name: Reboot
  when: udev_rename_netiface_config_changed.changed or ether_result.changed
  shell: sleep 2 && reboot
  async: 1
  poll: 0
  ignore_errors: true
- name: Wait for reboot
  when: udev_rename_netiface_config_changed.changed or ether_result.changed
  local_action: wait_for_connection delay=5
