- hosts: scripts-real
  serial: 1
  vars:
    network_ether_interfaces: "{{ lookup('template', 'templates/real_ether_interfaces.yml.j2') | from_yaml }}"
    ldap_server: "{{ run_local_ldap | default(True) | ternary('ldapi://%2fvar%2frun%2fslapd-scripts.socket/', 'ldap://scripts-ldap.mit.edu/') }}"
  pre_tasks:
    - include_role:
        name: network_interface
      vars:
        network_check_packages: False
    - name: Configure scripts RPM repos
      copy:
        dest: /etc/yum.repos.d/scripts.repo
        content: |
          [scripts]
          name=Scripts
          baseurl=http://web.mit.edu/scripts/yum-repos/rpm-fc{{ ansible_distribution_major_version }}/
          enabled=1
          gpgcheck=0

          [scripts-testing]
          name=Scripts Testing
          baseurl=http://web.mit.edu/scripts/yum-repos/rpm-fc{{ ansible_distribution_major_version }}-testing/
          enabled=0
          gpgcheck=0
  roles:
    - k5login
    - syslog-client
    - root-aliases
    - munin-node
    - real-nrpe
    - real-nsspam
    - real-sshd
    - real-postfix
    - mock
  # TODO: Configure aliases with blocked accounts and procmail for root
  tasks:
  - name: Hesiod
    block:
    #- name: Install hesiod
    #  dnf: name=hesiod-devel state=present
    - name: Configure hesiod
      copy:
        dest: /etc/hesiod.conf
        content: |
          rhs=.ATHENA.MIT.EDU
          lhs=.ns
  # TODO: Find package that provides lookup_hesiod.so or switch to another automounter
  - name: autofs
    block:
    - name: Install autofs
      dnf: name=autofs state=present
    - name: Configure autofs
      copy:
        dest: /etc/auto.master
        content: |
          /mit hesiod:hesiod
      notify: reload autofs
    - name: Enable autofs
      service:
        name: autofs
        enabled: yes
        state: started
  - name: Configure sudoers
    copy:
      dest: /etc/sudoers.d/scripts
      content: |
        scripts ALL=(root)      NOPASSWD: /usr/local/sbin/ldap-backup ""
        scripts ALL=(root)      NOPASSWD: /usr/local/sbin/get-homedirs ""
        scripts ALL=(root)      NOPASSWD: /etc/httpd/export-scripts-certs ""
        nrpe    ALL=(signup)    NOPASSWD: /etc/nagios/check_ldap_mmr.real
        pony    ALL=(root)      NOPASSWD: /etc/pki/tls/gencsr-pony

        Defaults:munin !syslog

        munin ALL=(root) SETENV: NOPASSWD: /etc/munin/plugins/postfix_mailqueue , /etc/munin/plugins/postfix_mailvolume , /etc/munin/plugins/hddtemp_smartctl , /etc/munin/plugins/sendmail* , /etc/munin/plugins/if_* , /etc/munin/plugins/if_err_eth2
        munin ALL=(root) NOPASSWD: /etc/munin/plugins/smart_*, /etc/munin/plugins/sensors_*
  - name: Configure sshd for scripts
    lineinfile:
      path: /etc/ssh/sshd_config
      regexp: '(?i)^#?\s*{{ item | regex_search("^(\S+)") }}\s'
      line: "{{ item }}"
    loop:
      # "PasswordAuthentication no" and "GSSAPIAuthentication yes" comes from the k5login role
      # "ChallengeResponseAuthentication yes" comes from the real-pam role
      - GSSAPICleanupCredentials yes
      - GSSAPIStrictAcceptorCheck no
      - GSSAPIKeyExchange yes
      - X11Forwarding no
      - Banner /etc/issue.net
      - LogLevel VERBOSE
      - MaxStartups 50:30:500
      - AcceptEnv LANG LC_CTYPE LC_NUMERIC LC_TIME LC_COLLATE LC_MONETARY LC_MESSAGES LC_PAPER LC_NAME LC_ADDRESS LC_TELEPHONE LC_MEASUREMENT LC_IDENTIFICATION LC_ALL EDITOR VISUAL
      # See trac #23
      - HostbasedAuthentication yes
      - IgnoreRhosts yes
      - IgnoreUserKnownHosts yes
      - DenyUsers {{ groups['scripts-real'] | map('regex_replace', '^', 'root@') | join(' ') }}
    notify: reload ssh
  - name: Limit Java memory
    lineinfile:
      path: /etc/environment
      line: JAVA_TOOL_OPTIONS="-Xmx128M -XX:MaxPermSize=64M"
      regexp: '^JAVA_TOOL_OPTIONS='
  - name: Configure resource limits
    copy:
      dest: /etc/security/limits.d/scripts
      content: |
        # No limits for root
        root             -
        scripts-build    -

        # For everyone else,
        *                soft    core            0
        *                -       rss             524268
        *                -       data            1048576
        *                -       as              1572864
  - name: Enable per-user logs
    ini_file:
      no_extra_spaces: yes
      path: /etc/systemd/journald.conf
      section: Journal
      option: SplitMode
      value: uid
    notify: restart journald
  handlers:
  - name: reload autofs
    service: name=autofs state=reloaded
  - name: restart journald
    service: name=systemd-journald state=restarted
