- hosts: scripts-proxy
  serial: 1
  pre_tasks:
  - include_role:
      name: proxy-network
  - name: Install packages
    package:
      name:
        - open-vm-tools
      state: present
  roles:
    - ansible-config-me
    - k5login
    - syslog-client
    - root-aliases
    - munin-node
    - nrpe
    - proxy-dns
    - proxy-haproxy
    # TODO: Configure logrotate
  tasks:
    - package:
        name:
          - vim
          - emacs-nox
        state: present
  handlers:
    - name: reboot
      include_tasks: reboot.yml
      listen: network changed
    - name: setup
      setup:
      listen: network changed
