- hosts: scripts-proxy
  serial: 1
  vars:
    network_allow_service_restart: false
    network_ether_interfaces:
    - device: vlan486
      hwaddr: "{{ vlan486_hwaddr | default(ansible_default_ipv4.macaddress) }}"
      cidr: "{{ vlan486_address | default(ansible_default_ipv4.address) }}/24"
      gateway: 18.4.86.1
      dns_nameservers: "{{ mit_dns_servers }}"
      dns_search: mit.edu
  pre_tasks:
  - include_role: name=udev_rename_netiface
  - include_role: name=network_interface
  - when: udev_rename_netiface_config_changed.changed or ether_result.changed
    command: "true"
    notify:
      - reboot
      - reconfigure munin-node
      - setup
  - name: Install packages
    apt:
      name:
        - open-vm-tools
      state: present
  roles:
    - k5login
    - syslog-client
    - root-aliases
    - munin-node
    - nrpe
  tasks:
    - copy:
        dest: /etc/apt/sources.list.d/backports.list
        content: |
          deb http://deb.debian.org/debian buster-backports main
          deb-src http://deb.debian.org/debian buster-backports main
    - apt:
        update_cache: yes
    - apt:
        name:
          - haproxy
        default_release: buster-backports
        state: present
    - apt:
        name:
          - hatop
          - haproxyctl
        state: present
    - apt:
        name:
          - vim
          - emacs-nox
        state: present
  handlers:
    - name: reboot
      include_tasks: reboot.yml
    - name: setup
      setup:
