# TODO: Install more PHP modules, consider disabling by default or just leaving them.
# TODO: Configure ssh host-based authentication
# TODO: Move blocked accounts into LDAP
# TODO: Configure a local 389-ds
# TODO: Configure /etc/hosts and routes so that sql.mit.edu goes over the backend network
# TODO: Fix rsyslog configuration so it spews all of authpriv, minus the blacklist of regexes
# TODO: Replace rc.local with something modern, if needed
# TODO: Install whoisd
# TODO: Build and install the rest of scripts-base
# TODO: Configure logwatch
# TODO: Make dnf drop setuid and caps on binaries we don't want to have them
# TODO: Select and install python packages (both Python 2 and Python 3)
# TODO: Select and install perl packages
# TODO: Select and install ruby packages
# TODO: Select and install $language packages

- hosts: scripts-real
  serial: 1
  vars:
    network_ether_interfaces: "{{ lookup('template', 'templates/real_ether_interfaces.yml.j2') | from_yaml }}"
    ldap_server: "{{ run_local_ldap | default(True) | ternary('ldapi://%2fvar%2frun%2fslapd-scripts.socket/', 'ldap://scripts-ldap.mit.edu/') }}"
  pre_tasks:
    - name: Install playbook Python dependencies
      dnf:
        name:
          - python3-netaddr
          - python3-dns
        state: present
    - name: Install network-scripts
      dnf:
        name: network-scripts
        state: present
    - include_role:
        name: network_interface
      vars:
        network_check_packages: False
    - name: Configure dnf
      block:
        - name: Configure scripts RPM repos
          copy:
            dest: /etc/yum.repos.d/scripts.repo
            content: |
              [scripts]
              name=Scripts
              baseurl=https://web.mit.edu/scripts/yum-repos/rpm-fc{{ ansible_distribution_major_version }}/
              enabled=1
              gpgcheck=0

              [scripts-testing]
              name=Scripts Testing
              baseurl=https://web.mit.edu/scripts/yum-repos/rpm-fc{{ ansible_distribution_major_version }}-testing/
              enabled=0
              gpgcheck=0
        - name: Configure dnf.conf
          ini_file:
            path: /etc/dnf/dnf.conf
            section: main
            option: "{{ item.option }}"
            value: "{{ item.value }}"
          loop:
            - option: installonly_limit
              value: 0
            - option: installonlypkgs
              value: kernel kernel-devel kernel-modules kmod-openafs ghc-cgi ghc-cgi-devel
  roles:
    - role: syslog-client
      when: syslog_client | default(True)
    - mock
    - sysctl
    - tmpfiles
    - real-munin-node
    - real-dns
    - real-ntp
    - real-ldap
    - real-k5login
    - real-nrpe
    - real-modprobe
    - real-nsspam
    - real-pki
    - real-iptables
    - real-sshd
    - real-postfix
    - real-afs
    - real-php
    - real-cron
    - role: real-httpd
      when: use_scripts_httpd | default(True)
      notify: reconfigure munin-node
    - real-logrotate
  tasks:
  - name: Editors
    block:
      - name: Install editors
        dnf:
          name:
            - vim
            - emacs-nox
          state: present
      - name: Disable viminfo
        lineinfile:
          path: /etc/vimrc
          regexp: '^set viminfo='
          line: "set viminfo=  \" don't keep a viminfo file"
  - name: Install accountadm
    dnf:
      name:
        - accountadm
      state: present
    when: use_accountadm | default(True)
  - name: execsys
    when: use_execsys | default(True)
    block:
      - name: Install execsys
        dnf: name=execsys state=present
      - name: Enable execsys services
        systemd:
          name: "{{ item }}"
          enabled: yes
          state: started
        loop:
          - execsys-binfmt.service
          - scripts-svn.socket
          - scripts-git.socket
          - scripts-local-smtp.socket
  - name: Hesiod
    block:
    - name: Install hesiod
      dnf: name=hesiod-devel state=present
      when: use_hesiod | default(True)
    - name: Configure hesiod
      copy:
        dest: /etc/hesiod.conf
        content: |
          rhs=.ATHENA.MIT.EDU
          lhs=.ns
  - name: Zephyr
    when: use_zephyr | default(True)
    block:
    - name: Install zephyr
      dnf: name=zephyr state=present
    - name: Start zephyr
      service:
        name: zhm
        enabled: yes
        state: started
  - name: autofs
    when: use_autofs | default(True)
    block:
    - name: Install autofs
      dnf: name=scripts-autofs state=present
    - name: Configure autofs
      copy:
        dest: /etc/auto.master
        content: |
          /mit hesiod:hesiod
      notify: reload autofs
    - name: Enable autofs
      service:
        name: autofs
        enabled: yes
        state: started
  - name: Configure sudoers
    copy:
      dest: /etc/sudoers.d/scripts
      content: |
        scripts ALL=(root)      NOPASSWD: /usr/local/sbin/ldap-backup ""
        scripts ALL=(root)      NOPASSWD: /usr/local/sbin/get-homedirs ""
  - name: Configure sshd for scripts
    lineinfile:
      path: /etc/ssh/sshd_config
      regexp: '(?i)^#?\s*{{ item | regex_search("^(\S+)") }}\s'
      line: "{{ item }}"
    loop:
      # "PasswordAuthentication no" and "GSSAPIAuthentication yes" comes from the k5login role
      # "ChallengeResponseAuthentication yes" comes from the real-pam role
      - GSSAPICleanupCredentials yes
      - GSSAPIStrictAcceptorCheck no
      - GSSAPIKeyExchange yes
      - X11Forwarding no
      - Banner /etc/issue.net
      - LogLevel VERBOSE
      - MaxStartups 50:30:500
      - AcceptEnv LANG LC_CTYPE LC_NUMERIC LC_TIME LC_COLLATE LC_MONETARY LC_MESSAGES LC_PAPER LC_NAME LC_ADDRESS LC_TELEPHONE LC_MEASUREMENT LC_IDENTIFICATION LC_ALL EDITOR VISUAL
      # See trac #23
      - HostbasedAuthentication yes
      - IgnoreRhosts yes
      - IgnoreUserKnownHosts yes
      - DenyUsers {{ groups['scripts-real'] | map('regex_replace', '^', 'root@') | join(' ') }}
    notify: reload ssh
  - name: Limit Java memory
    lineinfile:
      path: /etc/environment
      line: JAVA_TOOL_OPTIONS="-Xmx128M -XX:MaxPermSize=64M"
      regexp: '^JAVA_TOOL_OPTIONS='
  - name: Clean up kdump cores
    copy:
      dest: /etc/tmpfiles.d/scripts-crash.conf
      content: |
        d /var/crash 1755 root root 10d
    notify: create tmpfiles
  - name: Configure resource limits
    copy:
      dest: /etc/security/limits.d/scripts
      content: |
        # No limits for root
        root             -
        scripts-build    -

        # For everyone else,
        *                soft    core            0
        *                -       rss             524268
        *                -       data            1048576
        *                -       as              1572864
  - name: Enable per-user logs
    block:
    - name: Configure journald to split logs
      ini_file:
        no_extra_spaces: yes
        path: /etc/systemd/journald.conf
        section: Journal
        option: SplitMode
        value: uid
      notify: restart journald
    - name: Configure systemd user sessions to not log startup messages
      ini_file:
        no_extra_spaces: yes
        path: /etc/systemd/user.conf
        section: Manager
        option: LogLevel
        value: notice
  - name: grub
    block:
      - name: Configure grub
        ini_file:
          no_extra_spaces: yes
          path: /etc/default/grub
          section: null
          option: "{{ item.option }}"
          value: "\"{{ item.value }}\""
        loop:
          - option: GRUB_CMDLINE_LINUX
            value: "biosdevname=0 console=tty1 console=ttyS0 console=hvc0 rd.md=0 rd.lvm=0 rd.dm=0 rd.luks=0 crashkernel=128M"
          - option: GRUB_TERMINAL
            value: "serial console"
        notify: regenerate grub
  - name: Enable update e-mails
    block:
      - name: Install dnf-automatic
        dnf: name=dnf-automatic state=present
      - name: Configure dnf-automatic
        ini_file:
          path: /etc/dnf/automatic.conf
          section: "{{ item.section }}"
          option: "{{ item.option }}"
          value: "{{ item.value }}"
        loop:
          - section: commands
            option: download_updates
            value: "True"
          - section: commands
            option: apply_updates
            value: "False"
          - section: emitters
            option: emit_via
            value: stdio, command_email
          - section: command_email
            option: email_from
            value: root
          - section: command_email
            option: email_to
            value: root
      - name: Enable dnf-automatic
        systemd:
          name: dnf-automatic.timer
          enabled: yes
          state: started
  - name: Configure reboot on {panic,oops,OOM}
    copy:
      dest: /etc/sysctl.d/99-scripts-reboot.conf
      content: |
        kernel.panic = 5
        kernel.panic_on_oops = 1
        vm.panic_on_oom = 1
    notify: apply sysctl
  - name: Enable sysrq
    copy:
      dest: /etc/sysctl.d/99-scripts-sysrq.conf
      content: |
        kernel.sysrq = 1
    notify: apply sysctl
  - name: Configure multihomed networking sysctls
    copy:
      dest: /etc/sysctl.d/99-scripts-networking.conf
      content: |
        net.ipv4.ip_forward = 1
        net.ipv4.tcp_syncookies = 1
        net.ipv4.conf.default.accept_source_route = 0
        net.ipv4.conf.default.arp_ignore = 1
        net.ipv4.conf.default.arp_announce = 2
        net.ipv4.conf.all.arp_ignore = 1
        net.ipv4.conf.all.arp_announce = 2
        net.ipv4.conf.all.rp_filter = 2
        net.ipv4.tcp_keepalive_time = 825
    notify: apply sysctl
  - name: ClamAV
    block:
      - name: Install clamav
        dnf:
          name:
            - clamav
            - clamav-update
          state: present
  - name: User utilities
    block:
      - name: Install utilities
        dnf:
          name:
            - strace
            - ImageMagick
            - GraphicsMagick
          state: present
  handlers:
  - name: reload autofs
    service: name=autofs state=reloaded
  - name: restart journald
    service: name=systemd-journald state=restarted
  - name: regenerate grub
    command: grub2-mkconfig -o /boot/grub2/grub.cfg
