- hosts: scripts-real
  serial: 1
  roles:
    - k5login
    - syslog-client
    - root-aliases
    - munin-node
    - nrpe
    - real-pam
    - mock
  # TODO: Configure nrpe with realserver-specific checks
  # TODO: Configure aliases with blocked accounts and procmail for root
  tasks:
  - name: Hesiod
    block:
    #- name: Install hesiod
    #  dnf: name=hesiod-devel state=present
    - name: Configure hesiod
      copy:
        dest: /etc/hesiod.conf
        content: |
          rhs=.ATHENA.MIT.EDU
          lhs=.ns
  - name: autofs
    block:
    - name: Install autofs
      dnf: name=autofs state=present
    - name: Configure autofs
      copy:
        dest: /etc/auto.master
        content: |
          /mit hesiod:hesiod
      notify: reload autofs
  - name: Configure sudoers
    copy:
      dest: /etc/sudoers.d/scripts
      content: |
        scripts ALL=(root)      NOPASSWD: /usr/local/sbin/ldap-backup ""
        scripts ALL=(root)      NOPASSWD: /usr/local/sbin/get-homedirs ""
        scripts ALL=(root)      NOPASSWD: /etc/httpd/export-scripts-certs ""
        nrpe    ALL=(signup)    NOPASSWD: /etc/nagios/check_ldap_mmr.real
        pony    ALL=(root)      NOPASSWD: /etc/pki/tls/gencsr-pony

        Defaults:munin !syslog

        munin ALL=(root) SETENV: NOPASSWD: /etc/munin/plugins/postfix_mailqueue , /etc/munin/plugins/postfix_mailvolume , /etc/munin/plugins/hddtemp_smartctl , /etc/munin/plugins/sendmail* , /etc/munin/plugins/if_* , /etc/munin/plugins/if_err_eth2
        munin ALL=(root) NOPASSWD: /etc/munin/plugins/smart_*, /etc/munin/plugins/sensors_*
  - name: Configure sshd for scripts
    lineinfile:
      path: /etc/ssh/sshd_config
      regexp: '(?i)^#?\s*{{ item | regex_search("^(\S+)") }}\s'
      line: "{{ item }}"
    loop:
      # "PasswordAuthentication no" and "GSSAPIAuthentication yes" comes from the k5login role
      # "ChallengeResponseAuthentication yes" comes from the real-pam role
      - GSSAPICleanupCredentials yes
      - GSSAPIStrictAcceptorCheck no
      - GSSAPIKeyExchange yes
      - X11Forwarding no
      - Banner /etc/issue.net
      - LogLevel VERBOSE
      - MaxStartups 50:30:500
      - AcceptEnv LANG LC_CTYPE LC_NUMERIC LC_TIME LC_COLLATE LC_MONETARY LC_MESSAGES LC_PAPER LC_NAME LC_ADDRESS LC_TELEPHONE LC_MEASUREMENT LC_IDENTIFICATION LC_ALL EDITOR VISUAL
      # See trac #23
      - HostbasedAuthentication yes
      - IgnoreRhosts yes
      - IgnoreUserKnownHosts yes
      - DenyUsers {{ groups['scripts-real'] | map('regex_replace', '^', 'root@') | join(' ') }}
    notify: reload ssh
  - name: Limit Java memory
    lineinfile:
      path: /etc/environment
      line: JAVA_TOOL_OPTIONS="-Xmx128M -XX:MaxPermSize=64M"
      regexp: '^JAVA_TOOL_OPTIONS='
  - name: Configure resource limits
    copy:
      dest: /etc/security/limits.d/scripts
      contents: |
        # No limits for root
        root             -
        scripts-build    -

        # For everyone else,
        *                soft    core            0
        *                -       rss             524268
        *                -       data            1048576
        *                -       as              1572864
  handlers:
  - name: reload autofs
    service: name=autofs state=reloaded
