- hosts: scripts-directors
  serial: 1
  vars:
    network_allow_service_restart: false
    network_ether_interfaces:
    - device: vlan486
      hwaddr: "{{ vlan486_hwaddr }}"
      cidr: "{{ vlan486_address }}/24"
      gateway: 18.4.86.1
      dns_nameservers: "{{ mit_dns_servers }}"
      dns_search: mit.edu
    pacemaker_corosync_ring_interface: vlan486
    pacemaker_corosync_group: scripts-directors
  pre_tasks:
  - name: Install packages
    apt:
      name:
        - open-vm-tools
        - open-vm-tools-dkms
        - resolvconf
        - mlocate
        - lighttpd
        - lighttpd-mod-magnet
        - pacemaker
        - pacemaker-cli-utils
        - crmsh
        - ldirectord
        - aptitude
        - tcpdump
        - tshark
        - strace
        - emacs-nox
      state: present
  - systemd: name=ldirectord enabled=no
  - include_role: name=udev_rename_netiface
  - include_role: name=network_interface
  - when: udev_rename_netiface_config_changed.changed or ether_result.changed
    command: "true"
    notify:
      - reboot
      - reconfigure munin-node
      - setup
  roles:
  - k5login
  - syslog-client
  - root-aliases
  - ldirectord-status
  - lvs-iptables
  - lvs-lighttpd
  - lvs-ldirectord
  - lvs-munin-node
  - nrpe
  tasks:
  - name: Load IPVS modules
    copy:
      dest: /etc/modules-load.d/lvs.conf
      content: |
        ip_vs_dh
        ip_vs_ftp
        ip_vs
        ip_vs_lblc
        ip_vs_lblcr
        ip_vs_lc
        ip_vs_nq
        ip_vs_rr
        ip_vs_sed
        ip_vs_sh
        ip_vs_wlc
        ip_vs_wrr
    notify:
      - load modules
      - reload sysctl
  - name: Configure sysctl
    copy:
      dest: /etc/sysctl.d/lvs.conf
      content: |
        net.ipv4.ip_forward=1
        net.ipv4.vs.expire_quiescent_template = 1
        net.ipv4.conf.all.accept_local = 1
    notify: reload sysctl
  - name: "Install workaround for https://bugs.debian.org/808950"
    copy:
      dest: /usr/local/sbin/ipvsadm-hacked
      content: |
        #!/bin/sh
        [ "$1" != "--syncid" ] || shift 2  # https://bugs.debian.org/808950
        exec ipvsadm "$@"
      mode: 0755
  - name: Enable IPVS connection synchronization daemon
    copy:
      dest: /etc/default/ipvsadm
      content: |
        IPVSADM=/usr/local/sbin/ipvsadm-hacked  # https://bugs.debian.org/808950
        AUTO=false
        DAEMON=both
        IFACE=vlan486
    notify: restart ipvsadm
  - include_role: name=pacemaker-corosync
    vars:
      haveged_enabled: false
      pacemaker_enable_nodelist: false
  handlers:
  - name: load modules
    service: name=systemd-modules-load state=restarted
  - name: reload sysctl
    service: name=systemd-sysctl state=restarted
  - name: restart ipvsadm
    service: name=ipvsadm state=restarted
  - name: reboot
    include_tasks: reboot.yml
  - name: setup
    setup:
