- hosts: sql-buster
  serial: 1
  pre_tasks:
  - name: Install packages
    apt:
      name:
        - open-vm-tools
        # open-vm-tools-dkms removed in Debian 10
        - resolvconf
        - mlocate
        - aptitude
        - tcpdump
        - tshark
        - strace
        - emacs-nox
      state: present
  - include_role: name=systemd-networkd
  roles:
  - k5login
  - syslog-client
  - root-aliases
  - munin-node
  - nrpe
  handlers:
  - name: load modules
    service: name=systemd-modules-load state=restarted
  - name: reload sysctl
    service: name=systemd-sysctl state=restarted
  - name: reboot
    include_tasks: reboot.yml
  - name: setup
    setup:
