- hosts: sql-buster
  serial: 1
  pre_tasks:
  - name: Refuse to run on the primary
    fail:
      msg: Refusing to run on the primary
    when: lookup('dig', 'sql.mit.edu') in ansible_all_ipv4_addresses
  - name: Install packages
    apt:
      name:
        - open-vm-tools
        # open-vm-tools-dkms removed in Debian 10
        # resolvconf interacts poorly with systemd-networkd
        - mlocate
        - aptitude
        - tcpdump
        - tshark
        - strace
        - net-tools
        - emacs-nox
      state: present
  - include_role: name=systemd-networkd
  roles:
  - k5login
  - syslog-client
  - root-aliases
  - munin-node
  - sql-mysql
  - sql-remctl
  - sql-nrpe
  handlers:
  - name: load modules
    service: name=systemd-modules-load state=restarted
  - name: reload sysctl
    service: name=systemd-sysctl state=restarted
  - name: reboot
    include_tasks: reboot.yml
  - name: setup
    setup:
