- name: Create entry if missing
  ldap_entry:
    server_uri: "{{ ldap_instance_uri }}"
    dn: "{{ dn }}"
    objectClass: "{{ objectClass }}"
    attributes: "{{ attributes }}"
  notify: "{{ notify | default(omit) }}"
- name: Set attributes
  ldap_attr:
    server_uri: "{{ ldap_instance_uri }}"
    dn: "{{ dn }}"
    name: "{{ attribute.key }}"
    values: "{{ attribute.value }}"
    state: exact
  loop: "{{ attributes|dict2items }}"
  loop_control:
    loop_var: attribute
  notify: "{{ notify | default(omit) }}"
