---
- name: Install LDAP clients
  dnf:
    name:
      - openldap
      - ldapvi
    state: present
- name: Configure ldap.conf
  lineinfile:
    path: /etc/openldap/ldap.conf
    regexp: '(?i)^#?\s*{{ item | regex_search("^(\S+)") }}\s'
    line: "{{ item }}"
  loop:
    - BASE dc=scripts,dc=mit,dc=edu
    - URI {{ ldap_server }}
- name: Create /disabled
  file:
    path: /disabled
    state: directory
    mode: 0755
    owner: root
    group: root
- name: Install and configure 389-ds
  when: run_local_ldap
  vars:
    ldap_instance: scripts
    ldap_instance_uri: "ldapi://%2fvar%2frun%2fslapd-scripts.socket/"
  block:
    - name: Install 389-ds
      dnf:
        name:
          - 389-ds-base
        state: present
    - name: Create 389-ds instance
      command: python3 -
      args:
        creates: "/etc/dirsrv/slapd-{{ldap_instance}}"
        stdin: |
          import sys
          from lib389.cli_base import setup_script_logger
          from lib389.instance.setup import SetupDs
          from lib389.instance.options import General2Base, Slapd2Base, Backend2Base
          from lib389.properties import *

          verbose = True

          log = setup_script_logger("dscreate", verbose)
          
          sd = SetupDs(verbose, False, log)
          
          general = General2Base(log)
          general.set('start', False)
          
          slapd = Slapd2Base(log)
          slapd.set('instance_name', '{{ ldap_instance }}')
          slapd.set('self_sign_cert', False)
          slapd.set('root_password', '{PBKDF2_SHA256}bogushash')
          
          backend = {
            BACKEND_NAME: 'userRoot',
            BACKEND_SUFFIX: 'dc=scripts,dc=mit,dc=edu',
            'create_suffix_entry': False,
          }
          if not sd.create_from_args(general.collect(), slapd.collect(), [backend]):
            sys.exit(1)
    - name: Install scripts schema
      copy:
        dest: "/etc/dirsrv/slapd-{{ ldap_instance }}/schema/98scripts-vhost.ldif"
        src: 98scripts-vhost.ldif
    - name: Configure keytab
      copy:
        dest: "/etc/sysconfig/dirsrv-{{ ldap_instance }}"
        content: |
          KRB5_KTNAME=/etc/dirsrv/keytab
    - name: Start 389-ds
      service:
        name: "dirsrv@{{ ldap_instance }}"
        state: started
        enabled: yes
    - name: Configure GSSAPI authentication
      ldap_entry:
        server_uri: "{{ ldap_instance_uri }}"
        dn: "cn=mapname,cn=mapping,cn=sasl,cn=config"
        objectClass:
          - top
          - nsSaslMapping
        attributes:
          cn: mapname
          nsSaslMapRegexString: '\(.*\)'
          nsSaslMapBaseDNTemplate: 'uid=\1,ou=People,dc=scripts,dc=mit,dc=edu'
          nsSaslMapFilterTemplate: "(objectClass=posixAccount)"
    - name: Configure indices
      ldap_entry:
        server_uri: "{{ ldap_instance_uri }}"
        dn: "cn={{ item }},cn=index,cn=userRoot,cn=ldbm database,cn=plugins,cn=config"
        objectClass:
          - top
          - nsIndex
        attributes:
          cn: "{{ item }}"
          nsSystemIndex: "false"
          nsIndexType:
            - eq
            - pres
      loop:
        - scriptsVhostName
        - scriptsVhostAlias
        - scriptsVhostAccount
        - memberuid
        - uidnumber
        - gidnumber
      notify: reindex ldap
    - meta: flush_handlers
    - name: Create scripts domain
      ldap_entry:
        server_uri: "{{ ldap_instance_uri }}"
        dn: "dc=scripts,dc=mit,dc=edu"
        objectClass:
          - top
          - domain
        attributes:
          dc: scripts
    - name: Create People ou
      ldap_entry:
        server_uri: "{{ ldap_instance_uri }}"
        dn: "ou=People,dc=scripts,dc=mit,dc=edu"
        objectClass:
          - top
          - organizationalunit
        attributes:
          ou: People
    - name: Create users for LDAP servers
      ldap_entry:
        server_uri: "{{ ldap_instance_uri }}"
        dn: "uid=ldap/{{ item }},ou=People,dc=scripts,dc=mit,dc=edu"
        objectClass:
          - top
          - account
        attributes:
          uid: "ldap/{{ item }}"
      loop: "{{ groups['scripts-ldap'] }}"
    - name: Configure replica
      ldap_entry:
        server_uri: "{{ ldap_instance_uri }}"
        dn: 'cn=replica,cn=dc\3Dscripts\2Cdc\3Dmit\2Cdc\3Dedu,cn=mapping tree,cn=config'
        objectClass:
          - top
          - nsDS5Replica
        attributes:
          # Flags = 0 means the replica is read-only; if we want to be able to make changes, we need to set flags to 1 and initialize a changelog.
          nsDS5Flags: 0
          nsDS5ReplicaId: 65535
          nsDS5ReplicaBindDN: "{{ groups['scripts-ldap'] | map('regex_replace', '^(.*)$', 'uid=ldap/\\1,ou=People,dc=scripts,dc=mit,dc=edu') | list }}"
          nsDS5ReplicaType: 2
          nsDS5ReplicaRoot: dc=scripts,dc=mit,dc=edu
