---
- name: Install /etc/hosts
  blockinfile:
    path: /etc/hosts
    block: |
      {% for hostname in groups['sql'] + groups['scripts-real'] %}
      {% with info = hostvars[hostname] %}
      {% if info['ip'] | default(False) %}
      {{ info['ip'] }} {{ query('moira_ghal', hostname, include_short_names=True, include_cname=True)|join(' ') }}
      {% if info['vlan461_address'] | default(False) %}
      {{ info['vlan461_address'] }} {{ hostname }}
      {% endif %}
      {% endif %}
      {% endwith %}
      {% endfor %}

      {% for vip in vips %}
      {{ vip.ip }} {{ vip.host }} {{ vip.host | replace('.mit.edu', '') }}
      {% endfor %}
  when: use_moira
