---
- name: Install Perl modules
  dnf:
    name: "{{ lookup('file', 'perl.txt').splitlines() | map('regex_replace', '^(.*)$', 'perl(\\1)') | list}}"
    state: present
- name: Install Ruby gems
  dnf:
    name: "{{ lookup('file', 'rubygem.txt').splitlines() | map('regex_replace', '^(.*)$', 'rubygem(\\1)') | list}}"
    state: present
- name: Install scripts-specific Ruby gems
  dnf:
    name:
      - rubygem-fcgi
      - rubygem-pony
    state: present
  when: use_scripts_rubygems
# TODO: Consider forward-porting Ruby gems rack-mount, rack-ssl, will_paginate
# TODO: Consider updating Ruby gem compass to be installable
