---
- name: Install Perl modules
  dnf:
    name: "{{ lookup('file', 'perl.txt').splitlines() | map('regex_replace', '^(.*)$', 'perl(\\1)') | list}}"
    state: present
- name: Install Ruby gems
  dnf:
    name: "{{ lookup('file', 'rubygem.txt').splitlines() | map('regex_replace', '^(.*)$', 'rubygem(\\1)') | list}}"
    state: present
- name: Install scripts-specific Ruby gems
  dnf:
    name:
      - rubygem-fcgi
      - rubygem-pony
    state: present
  when: use_scripts_rubygems
- name: Install Python 2 libraries
  dnf:
    name: "{{ lookup('file', 'python2.txt').splitlines() | list}}"
    state: present
# TODO: Consider forward-porting missing Python packages
# TODO: Consider installing old Python 2 libraries from an old RPM repo
- name: Install Fedora 29 Python 2 libraryes
  dnf:
    name: "{{ lookup('file', 'python2-f29.txt').splitlines() | list}}"
    state: present
  when: ansible_distribution_major_version|int <= 29
# TODO: Consider forward-porting Ruby gems rack-mount, rack-ssl, will_paginate
# TODO: Consider updating Ruby gem compass to be installable
