---
- name: Install Perl modules
  dnf:
    name: "{{ lookup('file', 'perl.txt').splitlines() | map('regex_replace', '^(.*)$', 'perl(\\1)') | list}}"
    state: present
- name: Install Ruby gems
  dnf:
    name: "{{ lookup('file', 'rubygem.txt').splitlines() | map('regex_replace', '^(.*)$', 'rubygem(\\1)') | list}}"
    state: present
- name: Install scripts-specific Ruby gems
  dnf:
    name:
      - rubygem-fcgi
      - rubygem-pony
    state: present
  when: use_scripts_rubygems
- name: Install Python 2 libraries
  dnf:
    name: "{{ lookup('file', 'python2.txt').splitlines() | list}}"
    state: present
# TODO: Consider forward-porting missing Python packages
- name: Configure F29 repos as a source for old packages
  when: ansible_distribution_major_version|int >= 30
  block:
    - name: Configure F29 repos
      copy:
        dest: /etc/yum.repos.d/scripts-python2.repo
        content: |
          [scripts-f29]
          name=Fedora 29 - $basearch
          metalink=https://mirrors.fedoraproject.org/metalink?repo=fedora-29&arch=$basearch
          enabled=0
          metadata_expire=7d
          repo_gpgcheck=0
          type=rpm
          gpgcheck=1
          gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-fedora-29-$basearch
          [scripts-f29-updates]
          name=Fedora 29 - $basearch - Updates
          metalink=https://mirrors.fedoraproject.org/metalink?repo=updates-released-f29&arch=$basearch
          enabled=0
          repo_gpgcheck=0
          type=rpm
          gpgcheck=1
          metadata_expire=6h
          gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-fedora-29-$basearch
    - set_fact: f29_repos=scripts-f29,scripts-f29-updates
- name: Install Fedora 29 Python 2 libraries
  dnf:
    name: "{{ lookup('file', 'python2-f29.txt').splitlines() | list}}"
    enablerepo: "{{ f29_repos | default('') }}"
    state: present
# TODO: Update Python libraries for F29/F30 python packaging, and change default to on.
- name: Install scripts-specific Python 2 libraries
  dnf:
    name:
      - python2-afs
      - python2-hesiod
      - python2-moira
      - python2-zephyr
    state: present
  when: use_scripts_python2
# TODO: Package flipflop and/or flup6 for Python 3 as replacements for flup
# TODO: Package mechanize, MechnicalSoup, or robobrowser for Python 3
- name: Install Python 3 libraries
  dnf:
    name: "{{ lookup('file', 'python3.txt').splitlines() | list}}"
    state: present
# TODO: Consider forward-porting Ruby gems rack-mount, rack-ssl, will_paginate
# TODO: Consider updating Ruby gem compass to be installable
