---
- name: Install Perl modules
  dnf:
    name: "{{ lookup('file', 'perl.txt').splitlines() | map('regex_replace', '^(.*)$', 'perl(\\1)') | list}}"
    state: present
- name: Install Ruby gems
  dnf:
    name: "{{ lookup('file', 'rubygem.txt').splitlines() | map('regex_replace', '^(.*)$', 'rubygem(\\1)') | list}}"
    state: present
- name: Install scripts-specific Ruby gems
  dnf:
    name:
      - rubygem-fcgi
      - rubygem-pony
    state: present
  ignore_errors: yes
- name: Install PHP modules and libraries
  dnf:
    name: "{{ lookup('file', 'php.txt').splitlines() | list}}"
    state: present
- name: Install Python 2 libraries
  dnf:
    name: "{{ lookup('file', 'python2.txt').splitlines() | list}}"
    state: present
# TODO: Consider forward-porting missing Python packages
- name: Configure F29 repos as a source for old packages
  when: ansible_distribution_major_version|int >= 30
  block:
    - name: Configure F29 repos
      copy:
        dest: /etc/yum.repos.d/scripts-python2.repo
        content: |
          [scripts-f29]
          name=Fedora 29 - $basearch
          metalink=https://mirrors.fedoraproject.org/metalink?repo=fedora-29&arch=$basearch
          enabled=0
          metadata_expire=7d
          repo_gpgcheck=0
          type=rpm
          gpgcheck=1
          gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-fedora-29-$basearch
          [scripts-f29-updates]
          name=Fedora 29 - $basearch - Updates
          metalink=https://mirrors.fedoraproject.org/metalink?repo=updates-released-f29&arch=$basearch
          enabled=0
          repo_gpgcheck=0
          type=rpm
          gpgcheck=1
          metadata_expire=6h
          gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-fedora-29-$basearch
    - set_fact: f29_repos=scripts-f29,scripts-f29-updates
- name: Install Fedora 29 Python 2 libraries
  dnf:
    name: "{{ lookup('file', 'python2-f29.txt').splitlines() | list}}"
    enablerepo: "{{ f29_repos | default('') }}"
    state: present
# TODO: Update Python libraries for F29/F30 python packaging, and change default to on.
- name: Install scripts-specific Python 2 libraries
  dnf:
    name:
      - python2-afs
      - python2-hesiod
      - python2-moira
      - python2-zephyr
      - python2-authkit
    state: present
  ignore_errors: yes
- name: Install scripts-specific Python 3 libraries
  dnf:
    name:
      - python3-afs
      - python3-hesiod
      - python3-moira
      - python3-zephyr
    state: present
  ignore_errors: yes
# TODO: Package flipflop and/or flup6 for Python 3 as replacements for flup
# TODO: Package mechanize, MechnicalSoup, or robobrowser for Python 3
- name: Install Python 3 libraries
  dnf:
    name: "{{ lookup('file', 'python3.txt').splitlines() | list}}"
    state: present
- name: Install Fedora 30+ Python 3 libraries
  dnf:
    name: "{{ lookup('file', 'python3-f30.txt').splitlines() | list}}"
    state: present
  when: ansible_distribution_major_version|int >= 30
# TODO: Consider forward-porting Ruby gems rack-mount, rack-ssl, will_paginate
# TODO: Consider updating Ruby gem compass to be installable
- name: Install Glasgow Haskell Compiler
  dnf:
    name: "{{ lookup('file', 'ghc.txt').splitlines() | list}}"
    state: present
# TODO: Consider forward-porting Haskell libraries like ghc-cgi, ghc-editline, ghc-unix-handle
- name: Install NodeJS
  dnf:
    name: "{{ lookup('file', 'nodejs.txt').splitlines() | list}}"
    state: present
- name: Install Go
  dnf:
    name:
      - golang
    state: present
- name: Install Erlang
  dnf:
    name: "{{ lookup('file', 'erlang.txt').splitlines() | list}}"
    state: present
- name: Install texlive
  dnf:
    name:
      - rubber
      - texlive
      - texlive-collection-xetex
      - texlive-collection-luatex
      - texlive-collection-context
      - texlive-collection-binextra
      - texlive-collection-pstricks
      - texlive-collection-pictures
      - texlive-collection-fontutils
      - texlive-collection-fontsextra
      - texlive-collection-mathscience
      - texlive-collection-formatsextra
      - texlive-collection-metapost
      - tex-preview
    state: present
- name: Install C libraries
  dnf:
    name: "{{ lookup('file', 'libraries.txt').splitlines() | list}}"
    state: present
- name: Install Java
  dnf:
    name: "{{ lookup('file', 'java.txt').splitlines() | list}}"
    state: present
- name: Install Mono
  dnf:
    name: "{{ lookup('file', 'mono.txt').splitlines() | list}}"
    state: present
- name: Install utilities
  dnf:
    name: "{{ lookup('file', 'utilities.txt').splitlines() | list}}"
    state: present
- name: Install scripts development packages
  dnf:
    name:
      - athena-aclocal
      - openafs-authlibs-devel
      - openafs-docs
    state: present
  ignore_errors: yes
- name: Make sure packages in blacklist.txt are not present
  dnf:
    name: "{{ lookup('file', 'blacklist.txt').splitlines() | list}}"
    autoremove: yes
    disable_excludes: main
    state: absent
# TODO: Install all -devel packages for installed packages
