use_afs: "{{ 'fuse-better-mousetrapfs' in scripts_packages and 'openafs-client' in scripts_packages and 'kmod-openafs' in scripts_packages and 'tokensys' in scripts_packages }}"
afs_cache_size: 10000000
